#!/usr/bin/env python3
"""
Regenerate the "Kodama server - filesystem structure.md" reference file.

Runs a `tree` command for each directory listed in SECTIONS below and writes all
of the output into one markdown file, replacing whatever was there before.

If the markdown file already exists it is overwritten in place. No backups or
dated copies are made.

Usage:
    python3 update_kodama_structure.py                # refresh the .md in place
    python3 update_kodama_structure.py --dry-run      # print to stdout, write nothing
    python3 update_kodama_structure.py --list         # show the configured sections
    python3 update_kodama_structure.py -o other.md    # write somewhere else

To track a new directory (or change a depth), just edit SECTIONS.
"""

from __future__ import annotations

import argparse
import datetime as dt
import getpass
import os
import shutil
import socket
import subprocess
import sys
import tempfile
from pathlib import Path

# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

# Where the markdown file lives.
DEFAULT_OUTPUT = Path(
    "/home/wendy-wang/collisions-and-climate/Kodama server - file system structure.md"
)

# Each section = one directory + the tree flags to use for it.
# "args" are passed straight to `tree`, so anything tree accepts works
# (e.g. ["-L", "2", "-I", "__pycache__"]).
SECTIONS = [
    {
        "path": "/mnt",
        "args": ["-L", "1"],
    },
    {
        "path": "/mnt/data_d/Dropbox/Research/AnimalCollisionsWeather",
        "args": [],
    },
    {
        "path": "/mnt/data_f/AnimalCollisionsWeatherData",
        "args": [],
    },
    {
        "path": "/mnt/data_d/Dropbox/Research/UngulatePopulationDataRepo",
        "args": ["-L", "3"],
    },
    {
        "path": "/mnt/data_d/Dropbox/Research/VehicleCollisionsDataRepo",
        "args": ["-L", "3"],
    },
]

# Wrap each tree listing in a ``` code fence. Keeps the box-drawing characters
# lined up when the file is viewed as rendered markdown (Obsidian, GitHub, VS
# Code preview). Set to False for plain, unfenced output like the original file.
USE_CODE_FENCES = True

# Prompt string shown in each section heading, e.g. "wendy-wang@Kodama".
# Falls back to the current user/host if left as None.
PROMPT_LABEL = "wendy-wang@Kodama"


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------


def prompt_label() -> str:
    if PROMPT_LABEL:
        return PROMPT_LABEL
    try:
        user = getpass.getuser()
    except Exception:
        user = os.environ.get("USER", "user")
    host = socket.gethostname().split(".")[0]
    return f"{user}@{host}"


def check_tree_available() -> None:
    if shutil.which("tree") is None:
        sys.exit(
            "error: `tree` is not installed or not on PATH.\n"
            "       install it with:  sudo apt install tree"
        )


def run_tree(path: str, args: list[str]) -> tuple[str, str | None]:
    """Run tree in `path`. Returns (output, error_message_or_None)."""
    target = Path(path)
    if not target.exists():
        return "", f"directory does not exist: {path}"
    if not target.is_dir():
        return "", f"not a directory: {path}"

    try:
        proc = subprocess.run(
            ["tree", *args],
            cwd=str(target),
            capture_output=True,
            text=True,
            timeout=600,
        )
    except subprocess.TimeoutExpired:
        return "", f"tree timed out after 600s on {path}"
    except OSError as exc:
        return "", f"could not run tree on {path}: {exc}"

    out = proc.stdout.rstrip("\n")
    if proc.returncode != 0 and not out:
        detail = proc.stderr.strip() or f"exit code {proc.returncode}"
        return "", f"tree failed on {path}: {detail}"

    # tree writes permission problems etc. to stderr but still prints a tree.
    if proc.stderr.strip():
        out += "\n\n[stderr] " + proc.stderr.strip()

    return out, None


def build_markdown(sections: list[dict]) -> tuple[str, list[str]]:
    """Build the full markdown document. Returns (text, list_of_problems)."""
    label = prompt_label()
    stamp = dt.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %Z").strip()

    lines: list[str] = [
        "# Kodama server - filesystem structure",
        "",
        f"*Auto-generated by `update_kodama_structure.py` on {stamp}.*",
        "*Do not edit by hand - rerun the script instead.*",
        "",
    ]

    problems: list[str] = []

    for section in sections:
        path = section["path"]
        args = section.get("args", [])
        cmd = " ".join(["tree", *args]).strip()

        print(f"  {path}  ({cmd})", file=sys.stderr)
        output, error = run_tree(path, args)

        lines.append(f"## {label}:{path}$ {cmd}")
        lines.append("")

        if error:
            problems.append(error)
            lines.append(f"> **Not captured:** {error}")
            lines.append("")
            continue

        if USE_CODE_FENCES:
            lines.append("```text")
            lines.append(output)
            lines.append("```")
        else:
            lines.append(output)
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n", problems


def write_output(text: str, out_path: Path) -> None:
    """Write `text` to out_path, overwriting any existing file at that path."""
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Write to a temp file in the same directory, then os.replace() it onto the
    # target. os.replace overwrites atomically, so the existing .md is swapped
    # out in a single step: no backup, no duplicate, and an interrupted run
    # can never leave a half-written file behind.
    fd, tmp_name = tempfile.mkstemp(dir=str(out_path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp_name, out_path)
    except BaseException:
        if os.path.exists(tmp_name):
            os.unlink(tmp_name)
        raise


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Refresh the Kodama filesystem-structure markdown file.",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"output markdown file (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "-n",
        "--dry-run",
        action="store_true",
        help="print the markdown to stdout instead of writing the file",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="list the configured directories and exit",
    )
    args = parser.parse_args(argv)

    if args.list:
        for section in SECTIONS:
            cmd = " ".join(["tree", *section.get("args", [])]).strip()
            print(f"{section['path']}  ->  {cmd}")
        return 0

    check_tree_available()

    print("scanning:", file=sys.stderr)
    text, problems = build_markdown(SECTIONS)

    if args.dry_run:
        sys.stdout.write(text)
    else:
        existed = args.output.exists()
        write_output(text, args.output)
        print(
            f"{'overwrote' if existed else 'wrote'}: {args.output}",
            file=sys.stderr,
        )

    if problems:
        print(f"\n{len(problems)} section(s) had problems:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())